export interface PostFields {
  title: string;
  description: string;
  excerpt: string;
  date: string;
  tags: string[];
  featuredImage?: string;
}

export interface PostInput extends PostFields {
  body: string;
}

export function slugify(title: string): string {
  return title
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-+|-+$)/g, "");
}

/** Builds the .mdx source for a post from its fields. Only imports TestPromo if the body actually uses it. */
export function buildPostFile(input: PostInput): string {
  const needsTestPromo = /<TestPromo\b/.test(input.body);
  const importLine = needsTestPromo ? `import { TestPromo } from "@/components/blog/TestPromo";\n\n` : "";
  const featuredImageLine = input.featuredImage
    ? `\n  featuredImage: ${JSON.stringify(input.featuredImage)},`
    : "";
  const metadata = `export const metadata = {
  title: ${JSON.stringify(input.title)},
  description: ${JSON.stringify(input.description)},
  excerpt: ${JSON.stringify(input.excerpt)},
  date: ${JSON.stringify(input.date)},
  tags: ${JSON.stringify(input.tags)},${featuredImageLine}
};`;
  return `${importLine}${metadata}\n\n${input.body.trim()}\n`;
}

/** Reverses buildPostFile: pulls the metadata object and the markdown body back out of a post's raw source. */
export function parsePostFile(source: string): { metadata: PostFields; body: string } {
  const marker = "export const metadata = ";
  const metaStart = source.indexOf(marker);
  if (metaStart === -1) throw new Error("No metadata block found in post file");
  const metaEnd = source.indexOf("};", metaStart);
  if (metaEnd === -1) throw new Error("Malformed metadata block in post file");
  const metaSrc = source.slice(metaStart + marker.length, metaEnd + 1);
  // The object literal source is generated by buildPostFile above, not arbitrary user input, so evaluating it is safe.
  const metadata = new Function(`"use strict"; return (${metaSrc});`)() as PostFields;
  const body = source.slice(metaEnd + 2).replace(/^\s+/, "");
  return { metadata, body };
}

/** Adds a slug to the BLOG_SLUGS array in blog.ts's source, if it isn't already there. */
export function addSlugToRegistry(source: string, slug: string): string {
  if (source.includes(`"${slug}"`)) return source;
  return source.replace(
    /(export const BLOG_SLUGS = \[)([^\]]*)(\] as const;)/,
    (_match, open: string, inner: string, close: string) => {
      const trimmed = inner.trim();
      const sep = trimmed.length > 0 ? ", " : "";
      return `${open}${inner}${sep}"${slug}"${close}`;
    }
  );
}

/** Removes a slug from the BLOG_SLUGS array in blog.ts's source. */
export function removeSlugFromRegistry(source: string, slug: string): string {
  return source.replace(
    /(export const BLOG_SLUGS = \[)([^\]]*)(\] as const;)/,
    (_match, open: string, inner: string, close: string) => {
      const items = inner
        .split(",")
        .map((s) => s.trim())
        .filter((s) => s.length > 0 && s !== `"${slug}"`);
      return `${open}${items.join(", ")}${close}`;
    }
  );
}
